"""aboboka

Revision ID: 4a9196e67f25
Revises: 13913bf36866
Create Date: 2025-06-18 11:50:42.052753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a9196e67f25'
down_revision = '13913bf36866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.String(length=120), nullable=False))
        batch_op.drop_index(batch_op.f('Account_number'))
        batch_op.create_unique_constraint(None, ['account_number'])
        batch_op.drop_column('Account_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Account_number', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('Account_number'), ['Account_number'], unique=True)
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
